//! Shared DSP core for `VDco` and `VPolyDco`.
//!
//! One phase accumulator per voice drives saw, variable-width pulse, a
//! phase-locked ÷2 sub square, and a wavefolded triangle. Each waveform has
//! a continuous gain in `[0, 1]`. A white-noise source and an internal mixer
//! are folded into the same module so the output is a single pre-mixed signal.
//!
//! PolyBLEP corrections are applied at each waveshape's own discontinuities
//! and scale with the same gain as the raw waveform, preserving the
//! BLEP-to-raw ratio at any gain; the pulse comparator reads the raw phase
//! (never the BLEP-corrected saw), so duty cycle is bit-accurate.
//!
//! Triangle is generated by wavefolding the raw phase as
//! `tri = 1 - 2*|2*phase - 1|`, a standard absolute-value triangle at the fundamental (Jupiter
//! trick, fundamental variant). Its corners are C⁰ (slope discontinuities,
//! not value jumps), so no polyBLEP is used; residual aliasing is 6 dB/oct
//! below the saw and usually inaudible. A BLAMP refinement can be added
//! later if needed.

use patches_sdk::params_enum;
use patches_dsp::{fast_exp2, polyblep, xorshift64};

params_enum! {
    pub enum VDcoFmType {
        Linear => "linear",
        Logarithmic => "logarithmic",
    }
}

/// Linear FM scale — Hz per unit CV (matches `Osc`/`PolyOsc`).
const LINEAR_FM_HZ_PER_UNIT: f32 = 10.0;

/// Reference pitch: C0 ≈ 16.35 Hz. Duplicated from `patches-modules` to keep
/// `patches-vintage` free of the modules-crate dependency.
pub const C0_FREQ: f32 = 16.351_598;

/// Effective PWM range. Full travel (0 or 1) produces a DC-only pulse; the
/// clamp keeps the output audible at the extremes.
const PWM_MIN: f32 = 0.02;
const PWM_MAX: f32 = 0.98;

/// Internal scale on the noise source (≈ 0.5 full-scale at `noise_gain = 1`).
const NOISE_SCALE: f32 = 0.5;

/// Mixer settings (biased, not equal — worst-case sum ≈ 3.5× a single source).
#[derive(Clone, Copy)]
pub struct VDcoMix {
    pub saw_gain: f32,
    pub pulse_gain: f32,
    pub triangle_gain: f32,
    pub sub_gain: f32,
    pub noise_gain: f32,
    /// Always-on analog phasor curvature in `[0, 1]`. `0.0` is linear.
    pub curve: f32,
    /// Sync softness in `[0, 1]`. `0.0` = instant hard sync (0635 BLEP path).
    /// `> 0` uses an RC-discharge slew on sync; BLEP is skipped.
    pub sync_softness: f32,
}

impl VDcoMix {
    pub const DEFAULT: Self = Self {
        saw_gain: 1.0,
        pulse_gain: 0.0,
        triangle_gain: 0.0,
        sub_gain: 0.0,
        noise_gain: 0.0,
        curve: 0.1,
        sync_softness: 0.0,
    };
}

/// Quadratic approximation of the analog cap-charge curve, pinned at `0→0` and
/// `1→1`. `c = 0` reproduces the linear phasor bit-for-bit.
#[inline]
fn shape_phase(phase: f32, curvature: f32) -> f32 {
    phase - curvature * phase * (1.0 - phase)
}

/// Derivative of `shape_phase` w.r.t. phase — used to scale `dt` for polyBLEP.
#[inline]
fn shape_dt(dt: f32, phase: f32, curvature: f32) -> f32 {
    dt * (1.0 - curvature * (1.0 - 2.0 * phase))
}

/// Per-voice mutable state: phase, increment, sub flip-flop, noise PRNG.
pub struct VDcoVoice {
    pub phase: f32,
    pub phase_increment: f32,
    pub sub_flipflop: bool,
    pub prng_state: u64,
    /// Previous soft-sync output for the output-domain one-pole smoother.
    pub prev_soft_y: f32,
}

impl VDcoVoice {
    pub fn new(seed: u64) -> Self {
        Self {
            phase: 0.0,
            phase_increment: 0.0,
            sub_flipflop: false,
            // xorshift64 requires non-zero state.
            prng_state: seed.wrapping_add(1),
            prev_soft_y: 0.0,
        }
    }
}

/// Phase increment per sample for `voct` (V/oct relative to C0).
///
/// Clamped below 1.0 so `advance` can wrap with a single conditional subtract.
#[inline]
pub fn voct_to_increment(voct: f32, sample_rate: f32) -> f32 {
    let freq = C0_FREQ * fast_exp2(voct);
    (freq / sample_rate).min(0.999_999)
}

/// Phase increment from V/oct + FM, selecting linear vs logarithmic FM.
///
/// `base_voct` is the baseline frequency param (V/oct offset from C0) plus any
/// connected `voct` CV. `fm` is the raw FM CV (0 if disconnected). For
/// `Logarithmic`, FM adds to the exponent (1 V/oct). For `Linear`, FM adds
/// `LINEAR_FM_HZ_PER_UNIT` Hz per unit CV, matching `Osc`/`PolyOsc`.
#[inline]
pub fn compute_increment(
    base_voct: f32,
    fm: f32,
    fm_type: VDcoFmType,
    fm_connected: bool,
    sample_rate: f32,
) -> f32 {
    let exp = base_voct + if fm_connected && fm_type == VDcoFmType::Logarithmic { fm } else { 0.0 };
    let mut freq = C0_FREQ * fast_exp2(exp);
    if fm_connected && fm_type == VDcoFmType::Linear {
        freq += fm * LINEAR_FM_HZ_PER_UNIT;
    }
    // Clamp non-negative so `advance` never runs backwards, and below 1.0 per
    // sample so the wrap is a single conditional subtract.
    (freq / sample_rate).clamp(0.0, 0.999_999)
}

/// Advance the phase by `phase_increment`, wrapping to `[0, 1)`. Toggles the
/// sub flip-flop on each wrap so the ÷2 square stays phase-locked.
///
/// Returns the sub-sample fractional position of the wrap in `(0.0, 1.0]`
/// (ADR 0047 `Trigger` encoding), or `0.0` if no wrap occurred this sample.
/// The fractional position is measured from the start of the current sample:
/// `frac = (1 - phase_pre) / dt`, recovered post-wrap as `1 - phase_post / dt`.
#[inline]
pub fn advance(voice: &mut VDcoVoice) -> f32 {
    let dt = voice.phase_increment;
    let next = voice.phase + dt;
    if next >= 1.0 {
        voice.phase = next - 1.0;
        voice.sub_flipflop = !voice.sub_flipflop;
        // dt > 0 here since next >= 1.0 and voice.phase was in [0, 1).
        let frac = 1.0 - voice.phase / dt;
        // Clamp into (0, 1] so a near-zero frac still encodes as an event.
        frac.clamp(f32::MIN_POSITIVE, 1.0)
    } else {
        voice.phase = next;
        0.0
    }
}

/// Render one mixed sample for `voice` using the current phase, then advance.
///
/// `pwm` is the raw PWM CV (clamped internally). The saw, pulse, and sub all
/// derive from the same raw `phase`, each with its own polyBLEP correction.
///
/// Returns `(sample, wrap_frac)` where `wrap_frac` is the sub-sample position
/// of the natural phase wrap this sample (see [`advance`]), or `0.0` if no
/// wrap occurred.
#[inline]
pub fn render_and_advance(voice: &mut VDcoVoice, pwm: f32, mix: &VDcoMix) -> (f32, f32) {
    let lin_phase = voice.phase;
    let lin_dt = voice.phase_increment;
    let c = mix.curve;
    // Shaped phase drives all waveform reads; accumulator still runs linearly
    // so the perceived fundamental is unchanged.
    let phase = shape_phase(lin_phase, c);
    let dt = shape_dt(lin_dt, lin_phase, c);

    let mut y = 0.0_f32;

    if mix.saw_gain > 0.0 {
        y += mix.saw_gain * ((2.0 * phase - 1.0) - polyblep(phase, dt));
    }

    if mix.pulse_gain > 0.0 {
        let pwm_c = pwm.clamp(PWM_MIN, PWM_MAX);
        let raw = if phase < pwm_c { 1.0 } else { -1.0 };
        let blep = polyblep(phase, dt) - polyblep((phase - pwm_c).rem_euclid(1.0), dt);
        y += mix.pulse_gain * (raw + blep);
    }

    if mix.triangle_gain > 0.0 {
        // Wavefolded triangle at the fundamental: tri = 1 - 2*|2*phase - 1|.
        let tri = 1.0 - 2.0 * (2.0 * phase - 1.0).abs();
        y += mix.triangle_gain * tri;
    }

    if mix.sub_gain > 0.0 {
        // Sub: half-rate square phase-locked to main via the flip-flop. The
        // same curvature shape applies so the sub reads a shaped phase too.
        let lin_sub_phase = lin_phase * 0.5 + if voice.sub_flipflop { 0.5 } else { 0.0 };
        let lin_sub_dt = lin_dt * 0.5;
        let sub_phase = shape_phase(lin_sub_phase, c);
        let sub_dt = shape_dt(lin_sub_dt, lin_sub_phase, c);
        let raw = if sub_phase < 0.5 { 1.0 } else { -1.0 };
        let blep =
            polyblep(sub_phase, sub_dt) - polyblep((sub_phase - 0.5).rem_euclid(1.0), sub_dt);
        y += mix.sub_gain * (raw + blep);
    }

    if mix.noise_gain > 0.0 {
        let w = xorshift64(&mut voice.prng_state);
        y += mix.noise_gain * NOISE_SCALE * w;
    }

    let wrap_frac = advance(voice);
    (y, wrap_frac)
}

/// Render one mixed sample with a sync event at sub-sample offset `frac`.
///
/// `frac ∈ (0.0, 1.0]` is the position within this sample where the sync
/// event fired (ADR 0047 `Trigger` encoding). The phase advances linearly to
/// the event point, each active waveform's pre-reset value is captured, then
/// phase resets to `0` and sub-flipflop to `false`, phase advances to
/// `(1 - frac) * dt`, and each waveform applies a PolyBLEP residual at that
/// offset scaled by its own `Δ = pre - post` jump. The pulse jump is handled
/// as a single combined `Δ` (no separate comparator BLEP). Triangle is C⁰ so
/// no BLEP is applied; its value jump is represented implicitly.
///
/// Does not emit a wrap-frac on `reset_out`: the sync sample is not a
/// natural wrap.
#[inline]
pub fn render_sync_and_advance(
    voice: &mut VDcoVoice,
    frac: f32,
    pwm: f32,
    mix: &VDcoMix,
) -> f32 {
    // Guard against degenerate frac values.
    let frac = frac.clamp(f32::MIN_POSITIVE, 1.0);
    let dt = voice.phase_increment;
    let c = mix.curve;
    let pwm_c = pwm.clamp(PWM_MIN, PWM_MAX);

    // Pre-sync linear phase at the event (the pulse comparator always reads
    // raw phase — never BLEP-corrected saw — so we derive pre-values from it).
    let mut lin_pre = voice.phase + frac * dt;
    let pre_flipflop = if lin_pre >= 1.0 {
        lin_pre -= 1.0;
        !voice.sub_flipflop
    } else {
        voice.sub_flipflop
    };
    let pre_phase = shape_phase(lin_pre, c);
    let pre_saw = 2.0 * pre_phase - 1.0;
    let pre_pulse = if pre_phase < pwm_c { 1.0 } else { -1.0 };
    let lin_pre_sub = lin_pre * 0.5 + if pre_flipflop { 0.5 } else { 0.0 };
    let pre_sub_phase = shape_phase(lin_pre_sub, c);
    let pre_sub = if pre_sub_phase < 0.5 { 1.0 } else { -1.0 };

    // Reset and advance to the remainder of the sample.
    voice.sub_flipflop = false;
    let lin_post = (1.0 - frac) * dt;
    voice.phase = lin_post;

    let post_phase = shape_phase(lin_post, c);
    let post_dt = shape_dt(dt, lin_post, c);
    let post_saw = 2.0 * post_phase - 1.0;
    let post_pulse = if post_phase < pwm_c { 1.0 } else { -1.0 };
    let post_tri = 1.0 - 2.0 * (2.0 * post_phase - 1.0).abs();
    let lin_post_sub = lin_post * 0.5; // sub_flipflop == false → no half offset
    let post_sub_phase = shape_phase(lin_post_sub, c);
    let post_sub_dt = shape_dt(dt * 0.5, lin_post_sub, c);
    let post_sub = if post_sub_phase < 0.5 { 1.0 } else { -1.0 };

    // Canonical polyBLEP residual for a Δ = +2 discontinuity at sub-sample
    // offset `frac` from the sample start (i.e. `1 - frac` before the next
    // sample boundary, so phase distance past the jump is `(1 - frac) * dt`).
    // Scale by `Δ / 2` per waveform where `Δ = pre - post`.
    let blep_saw = polyblep(lin_post, post_dt) * 0.5;
    let blep_sub = polyblep(lin_post_sub, post_sub_dt) * 0.5;

    let mut y = 0.0_f32;

    if mix.saw_gain > 0.0 {
        let delta = pre_saw - post_saw;
        y += mix.saw_gain * (post_saw + blep_saw * delta);
    }

    if mix.pulse_gain > 0.0 {
        let delta = pre_pulse - post_pulse;
        y += mix.pulse_gain * (post_pulse + blep_saw * delta);
    }

    if mix.triangle_gain > 0.0 {
        y += mix.triangle_gain * post_tri;
    }

    if mix.sub_gain > 0.0 {
        let delta = pre_sub - post_sub;
        y += mix.sub_gain * (post_sub + blep_sub * delta);
    }

    if mix.noise_gain > 0.0 {
        let w = xorshift64(&mut voice.prng_state);
        y += mix.noise_gain * NOISE_SCALE * w;
    }

    y
}

/// Render one sample under the soft-sync (partial cap-discharge) model.
///
/// Used only when `mix.sync_softness > 0`. On a sync event the integrator
/// cap is only partially discharged: phase is scaled by a residual factor
/// `residual = softness²`, so `softness → 0` approaches hard reset (phase → 0)
/// and `softness → 1` approaches no reset. Phase only ever moves forward —
/// no backward sweep through the waveform, so pulse/triangle edges are not
/// re-crossed and integer sync ratios stay clean.
///
/// The sub flip-flop is a digital divider downstream of the core; a partial
/// discharge that does not cross zero does not toggle it, so `sub_flipflop`
/// is left alone on the sync event. Natural-wrap BLEP is retained via
/// `render_and_advance`.
///
/// Returns `(sample, wrap_frac)`. On a sync sample, `wrap_frac = 0.0`.
#[inline]
pub fn render_and_advance_soft(
    voice: &mut VDcoVoice,
    sync: Option<f32>,
    pwm: f32,
    mix: &VDcoMix,
) -> (f32, f32) {
    let softness = mix.sync_softness.clamp(0.0, 1.0);
    if sync.is_some() {
        // Cap residual below 1 so even maximum softness still discharges the
        // integrator partially on each sync pulse (matches physical RC: pulse
        // width is always > 0, so full voltage retention is not reachable).
        let residual = (softness * softness).min(0.95);
        voice.phase *= residual;
    }
    let (y_raw, wrap_frac) = render_and_advance(voice, pwm, mix);
    // Post-VCO output-domain one-pole to model the finite-bandwidth analog
    // buffer stage that smears the cap-discharge transient. τ scales with
    // softness² so softness=0 is bypass and softness=1 is the strongest smear.
    let tau = softness * softness * 2.0;
    let a = if tau > 0.0 { (-1.0 / tau).exp() } else { 0.0 };
    let y = a * voice.prev_soft_y + (1.0 - a) * y_raw;
    voice.prev_soft_y = y;
    let wrap_frac = if sync.is_some() { 0.0 } else { wrap_frac };
    (y, wrap_frac)
}
